(() => {
  const APP_ID = "safe-confirm-helper";
  const STORE = `${APP_ID}:settings`;
  const BTN = "button,[role='button'],input[type='button'],input[type='submit']";
  const DLG = "dialog[open],[role='dialog'],[role='alertdialog'],[aria-modal='true'],[data-radix-dialog-content],[data-headlessui-state],.modal,.popover";
  const CONTINUE = "继续原始任务。优先处理未完成、未验证或有风险的部分。不要总结；不要只说“任务已完成”。若确认全部完成，输出 SCH_FINAL，否则继续执行。";
  const AUDIT = "先不要结束。现在做最终自检：1. 原始需求是否有遗漏？2. 哪些完成声明缺少证据？3. 哪些只是推测而非验证？4. 是否还有阻塞风险？如有任何阻塞项，继续修复；只有没有遗漏和未验证项时，才输出 SCH_FINAL。";
  const SUPERVISE = `[SafeConfirm Supervision]\n本任务按长任务处理。不要用一句“任务已完成”结束。\n执行时优先完成原始需求；停止前必须自检是否有遗漏、未验证项和阻塞风险。\n如果仍有未完成或未验证项，继续执行。\n如果确认可以结束，只输出 SCH_FINAL 块，说明覆盖项、证据、未验证项和风险。`;
  const DEF = { enabled: true, autoConfirm: true, keepAtBottom: true, autoContinue: true, superviseLongTasks: true, english: true, highlight: true, continuePrompt: CONTINUE, maxContinueCount: 50, continueCooldownMs: 10000, auditEvery: 3, userScrollPauseMs: 12000 };
  const ZH = [/^确认$/, /^允许$/, /^继续$/, /^批准$/, /确认/, /允许/, /批准/, /继续/];
  const EN = [/^Confirm$/i, /^Approve$/i, /^Allow$/i, /^Continue$/i, /^Accept$/i, /\bConfirm\b/i, /\bApprove\b/i, /\bAllow\b/i, /\bContinue\b/i, /\bAccept\b/i];
  const FIELDS = ["status", "covered", "proof", "unverified", "risks", "verdict"];
  const old = window.__safeConfirmHelperCleanup;
  if (typeof old === "function") old();
  const ac = new AbortController();
  const timers = new Set();
  let settings = { ...DEF };
  let observer, scanTimer = 0, assistTimer = 0, scanLoop = 0, assistLoop = 0, candidate = null;
  let clicked = new WeakSet();
  let lastHiddenScan = 0, lastHiddenAssist = 0, lastUserScroll = 0, programmaticScrollUntil = 0;
  let scanInfo = { roots: 0, candidates: 0, matches: 0 };
  const runtime = { continueCount: 0, sendFailureCount: 0, lastContinueAt: 0, lastAssistantTextHash: "", pausedReason: "" };
  let task = blankTask();

  function blankTask() { return { active: false, status: "idle", taskId: "", startedAt: 0, loopCount: 0, auditCount: 0, lastFinal: null, lastGateReason: "", stopReason: "" }; }
  function norm(v) { return String(v || "").replace(/\u0000/g, "").replace(/\s+/g, " ").trim(); }
  function hash(v) { let h = 2166136261; v = String(v || ""); for (let i = 0; i < v.length; i++) { h ^= v.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0).toString(36); }
  function cjk(v) { const m = String(v || "").match(/[\u3400-\u9fff\uf900-\ufaff]/g); return m ? m.length : 0; }
  function delay(fn, ms) { const id = setTimeout(() => { timers.delete(id); fn(); }, ms); timers.add(id); return id; }
  function every(fn, ms) { const id = setInterval(fn, ms); timers.add(id); return id; }
  function clear(id) { if (!id) return; clearTimeout(id); clearInterval(id); timers.delete(id); }
  function clamp(v, min, max, fallback) { const n = parseInt(v, 10); return Number.isFinite(n) ? Math.min(max, Math.max(min, n)) : fallback; }
  function cleanSettings(v) { v = v && typeof v === "object" ? v : {}; const s = {}; Object.keys(DEF).forEach((k) => s[k] = v[k] ?? DEF[k]); s.maxContinueCount = clamp(s.maxContinueCount, 1, 200, 50); s.continueCooldownMs = clamp(s.continueCooldownMs, 1000, 120000, 10000); s.auditEvery = clamp(s.auditEvery, 1, 20, 3); s.userScrollPauseMs = clamp(s.userScrollPauseMs, 1000, 60000, 12000); s.continuePrompt = String(s.continuePrompt || CONTINUE).trim() || CONTINUE; return s; }
  async function loadSettings() { try { const cur = await chrome.storage.local.get(["settings", "migratedFromLocalStorage"]); if (!cur.migratedFromLocalStorage) { const raw = localStorage.getItem(STORE); if (raw && !cur.settings) await chrome.storage.local.set({ settings: cleanSettings(JSON.parse(raw)) }); await chrome.storage.local.set({ migratedFromLocalStorage: true }); } const result = await chrome.storage.local.get(["settings"]); return cleanSettings(result.settings); } catch { try { return cleanSettings(JSON.parse(localStorage.getItem(STORE) || "{}")); } catch { return cleanSettings({}); } } }
  async function saveSettings() { settings = cleanSettings(settings); try { await chrome.storage.local.set({ settings }); } catch { localStorage.setItem(STORE, JSON.stringify(settings)); } }
  function visible(el) { if (!el || !el.isConnected) return false; const s = getComputedStyle(el); if (s.display === "none" || s.visibility === "hidden" || s.opacity === "0" || s.pointerEvents === "none") return false; const r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0 && r.bottom >= 0 && r.right >= 0 && r.top <= innerHeight && r.left <= innerWidth; }
  function enabled(el) { return !!(el && !el.disabled && el.getAttribute("aria-disabled") !== "true" && visible(el)); }
  function text(el) { if (!el) return ""; const a = el.getAttribute?.("aria-label") || el.getAttribute?.("title"); const v = el.getAttribute?.("value"); return [...new Set([a, v, el.textContent, el.innerText].filter(Boolean).map((x) => x.trim()).filter(Boolean))].join(" ").replace(/\s+/g, " ").trim(); }
  function click(el) { if (typeof PointerEvent === "function") el.dispatchEvent(new PointerEvent("pointerdown", { bubbles: true, cancelable: true })); el.dispatchEvent(new MouseEvent("mousedown", { bubbles: true, cancelable: true })); if (typeof PointerEvent === "function") el.dispatchEvent(new PointerEvent("pointerup", { bubbles: true, cancelable: true })); el.dispatchEvent(new MouseEvent("mouseup", { bubbles: true, cancelable: true })); el.click(); }
  function toast(msg) { document.getElementById(`${APP_ID}-toast`)?.remove(); const el = document.createElement("div"); el.id = `${APP_ID}-toast`; el.textContent = msg; Object.assign(el.style, { position: "fixed", left: "50%", bottom: "92px", transform: "translateX(-50%)", zIndex: "2147483647", background: "rgba(17,24,39,.92)", color: "#fff", padding: "10px 14px", borderRadius: "8px", fontSize: "14px", fontFamily: "system-ui,sans-serif", boxShadow: "0 6px 18px rgba(0,0,0,.2)" }); document.documentElement.appendChild(el); delay(() => el.remove(), 1800); }

  function buttonPatterns() { return settings.english ? ZH.concat(EN) : ZH; }
  function buttonMatch(el) { const s = text(el); return !!s && buttonPatterns().some((p) => p.test(s)); }
  function score(el) { const s = text(el); let n = 0; if (/确认|confirm/i.test(s)) n += 5; if (/批准|approve/i.test(s)) n += 4; if (/允许|allow/i.test(s)) n += 3; if (/继续|continue/i.test(s)) n += 2; if (el.closest(DLG)) n += 6; return n; }
  function clearMark() { const el = document.querySelector('[data-safe-confirm-helper-highlight="true"]'); if (!el) return; el.style.outline = el.dataset.safeConfirmHelperOldOutline || ""; el.style.outlineOffset = el.dataset.safeConfirmHelperOldOutlineOffset || ""; el.removeAttribute("data-safe-confirm-helper-highlight"); }
  function mark() { if (!settings.highlight || !candidate) return; candidate.dataset.safeConfirmHelperOldOutline = candidate.style.outline; candidate.dataset.safeConfirmHelperOldOutlineOffset = candidate.style.outlineOffset; candidate.setAttribute("data-safe-confirm-helper-highlight", "true"); candidate.style.outline = "2px solid #22c55e"; candidate.style.outlineOffset = "3px"; }
  function setCandidate(btn) { if (candidate === btn) return; clearMark(); candidate = btn; if (!btn) clicked = new WeakSet(); mark(); }
  function scan() { if (!settings.enabled) { setCandidate(null); return null; } const roots = Array.from(document.querySelectorAll(DLG)).filter(visible).slice(-4); if (!roots.length) roots.push(document.body || document.documentElement); let best = null, bestScore = -1, total = 0, matches = 0; for (const root of roots) { const list = root.querySelectorAll(BTN); total += list.length; for (const b of list) { if (!enabled(b) || !buttonMatch(b)) continue; matches++; const n = score(b); if (n > bestScore) { best = b; bestScore = n; } } } scanInfo = { roots: roots.length, candidates: total, matches }; setCandidate(best); autoClick(); return best; }
  function requestScan() { if (settings.autoConfirm && document.visibilityState === "hidden") { const now = Date.now(); if (now - lastHiddenScan < 250) return; lastHiddenScan = now; scan(); return; } if (scanTimer) return; scanTimer = delay(() => { scanTimer = 0; scan(); }, 120); }
  function autoClick() { if (!settings.autoConfirm || !candidate || clicked.has(candidate) || !enabled(candidate) || !buttonMatch(candidate)) return false; const label = text(candidate); click(candidate); clicked.add(candidate); toast(`已自动确认：「${label}」`); requestScan(); return true; }
  function manualClick() { const b = candidate && enabled(candidate) && buttonMatch(candidate) ? candidate : scan(); if (!b) return toast("没有找到可见的确认按钮"); const label = text(b); if (confirm(`是否点击按钮：「${label}」？`)) { click(b); toast(`已点击：「${label}」`); requestScan(); } }

  function input(scope = document) { return [...(scope.querySelectorAll?.("#prompt-textarea,textarea,[contenteditable='true']") || []), ...document.querySelectorAll("#prompt-textarea,textarea,[contenteditable='true']")].filter(visible).find((el) => !el.closest(`#${APP_ID}-panel`)) || null; }
  function inputText(el) { return !el ? "" : ("value" in el ? String(el.value || "") : String(el.textContent || "")).trim(); }
  function setInput(el, value) { if (!el) return false; el.focus(); if ("value" in el) { const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el), "value")?.set; setter ? setter.call(el, value) : el.value = value; el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertText", data: value })); el.dispatchEvent(new Event("change", { bubbles: true })); return true; } const sel = getSelection(); if (sel) { const r = document.createRange(); r.selectNodeContents(el); sel.removeAllRanges(); sel.addRange(r); document.execCommand("insertText", false, value); } if (inputText(el) !== value) el.textContent = value; el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertText", data: value })); return inputText(el) === value; }
  function sendButton(el) { const form = el?.closest?.("form"); for (const sel of ["button[data-testid='send-button']", "button[aria-label*='发送']", "button[aria-label*='Send']", "button[title*='发送']", "button[title*='Send']"]) { const b = (form || document).querySelector(sel); if (b && enabled(b)) return b; } const submit = (form || document).querySelector("button[type='submit']"); if (submit && enabled(submit)) return submit; return Array.from((form || document).querySelectorAll(BTN)).filter(enabled).find((b) => /发送|send/i.test(text(b))) || null; }
  function queuePrompt(prompt, sent, failed) { const el = input(); if (!el || !visible(el) || inputText(el)) return false; if (!setInput(el, prompt)) return false; delay(() => trySend(el, 0, sent, failed), 120); return true; }
  function trySend(el, attempt, sent, failed) { const b = sendButton(el); if (b && enabled(b)) { click(b); sent?.(); return true; } if (attempt < 2) return delay(() => trySend(el, attempt + 1, sent, failed), 700), false; failed?.(); return false; }

  function lastAssistantEl() { const direct = [...document.querySelectorAll("[data-message-author-role='assistant']")].filter(visible); if (direct.length) return direct.at(-1); const msgs = [...document.querySelectorAll("article,[data-testid*='conversation-turn']")].filter(visible); for (let i = msgs.length - 1; i >= 0; i--) { const role = msgs[i].getAttribute("data-message-author-role"); if (role === "user") continue; if (role === "assistant" || !msgs[i].querySelector("textarea,[contenteditable='true']")) return msgs[i]; } return null; }
  function lastAssistantText() { return text(lastAssistantEl()); }
  function running() { const buttons = Array.from(document.querySelectorAll(BTN)).filter(visible); return buttons.some((b) => /停止|中止|stop|cancel/i.test(text(b))) || /正在思考|正在运行|正在生成|thinking|running|generating/i.test(lastAssistantText()); }
  function shouldSupervise(s) { const n = norm(s), lower = n.toLowerCase(); if (!n) return false; if (/https?:\/\/|github\.com\/|vercel\.app|www\./i.test(n)) return true; const words = ["继续", "直到完成", "不要停", "全部完成", "完整", "优化", "审计", "实现", "修改", "重构", "开发计划", "部署", "构建", "运行", "验证", "检查", "seo", "cro", "ux", "github", "vercel", "sitemap", "robots", "代码", "项目", "仓库", "插件"]; const hasWord = words.some((w) => lower.includes(w)); const multi = /[1-9][.、)]|第一|第二|第三|步骤|阶段|要求|必须|不要|全部/.test(n); return ((cjk(n) >= 80 || n.length >= 120) && hasWord) || (hasWord && multi); }
  function pluginPrompt(s) { const n = norm(s); return n === norm(CONTINUE) || n === norm(AUDIT) || n.includes("现在做最终自检") || n.includes("继续原始任务"); }
  function prepare(el) { if (!settings.enabled || !settings.superviseLongTasks) return false; const s = inputText(el); if (!s || pluginPrompt(s) || s.includes("[SafeConfirm Supervision]") || !shouldSupervise(s)) return false; if (!setInput(el, `${s.trim()}\n\n${SUPERVISE}`)) return false; task = { active: true, status: "supervising", taskId: `${Date.now().toString(36)}-${hash(s)}`, startedAt: Date.now(), loopCount: 0, auditCount: 0, lastFinal: null, lastGateReason: "", stopReason: "" }; Object.assign(runtime, { continueCount: 0, sendFailureCount: 0, lastContinueAt: 0, lastAssistantTextHash: "", pausedReason: "" }); toast("已进入长任务监督"); return true; }

  function parseFinal(s) { const m = String(s || "").match(/<SCH_FINAL>([\s\S]*?)<\/SCH_FINAL>/i); if (!m) return null; const body = m[1].trim(), out = { raw: body }; for (const f of FIELDS) out[f] = field(body, f); return out; }
  function field(body, name) { const names = FIELDS.join("|"); const m = String(body || "").match(new RegExp(`^\\s*${name}\\s*:\\s*([\\s\\S]*?)(?=^\\s*(?:${names})\\s*:|$)`, "im")); return m ? m[1].trim() : ""; }
  function empty(v) { return ["", "none", "no", "无", "没有", "空", "n/a", "na"].includes(norm(v).toLowerCase()); }
  function block(v) { return /阻塞|高风险|未验证|未测试|未运行|无法确认|需要.*确认|not verified|not tested|not run|cannot confirm|need.*confirmation/i.test(String(v || "")); }
  function gate(f) { if (!f) return { canStop: false, reason: "missing_final" }; for (const k of FIELDS) if (!String(f[k] || "").trim()) return { canStop: false, reason: `missing_${k}` }; if (!/^done$/i.test(norm(f.status))) return { canStop: false, reason: "status_not_done" }; if (!/ready_to_stop/i.test(norm(f.verdict))) return { canStop: false, reason: "verdict_not_ready" }; if (!empty(f.unverified)) return { canStop: false, reason: "unverified_exists" }; if (!empty(f.risks) && block(f.risks)) return { canStop: false, reason: "blocking_risk_exists" }; if (block(f.raw)) return { canStop: false, reason: "blocking_keyword_in_final" }; return { canStop: true, reason: "valid_final" }; }
  function auditNeeded(s, g) { return /任务已完成|已完成|完成了|done|completed|finished|ready_to_stop|未验证|未测试|未运行|无法确认|需要你确认|可能|大概|理论上|应该|not verified|not tested|cannot confirm|need confirmation|probably|maybe|should/i.test(String(s || "")) || ["unverified_exists", "blocking_risk_exists", "blocking_keyword_in_final"].includes(g.reason) || (task.loopCount > 0 && task.loopCount % settings.auditEvery === 0); }
  function maybeContinue() { if (!settings.enabled || !settings.autoContinue || !settings.superviseLongTasks || !task.active || runtime.pausedReason) return false; if (runtime.continueCount >= settings.maxContinueCount) { runtime.pausedReason = `已达到最大自动继续次数 ${settings.maxContinueCount}`; task.status = "paused_max_continue"; return false; } const last = lastAssistantText(); if (!last || running()) return false; if (Date.now() - runtime.lastContinueAt < settings.continueCooldownMs) return false; const h = hash(last); if (runtime.lastAssistantTextHash === h) return false; const f = parseFinal(last), g = gate(f); task.lastFinal = f; task.lastGateReason = g.reason; if (g.canStop) { task.active = false; task.status = "stopped_valid_final"; task.stopReason = "合格 SCH_FINAL 已出现"; toast("已达到自验证停止条件"); return false; } const el = input(); if (!el || !visible(el) || inputText(el)) return false; const audit = auditNeeded(last, g); task.status = audit ? "auditing" : "continuing"; if (audit) task.auditCount++; return queuePrompt(audit ? AUDIT : (settings.continuePrompt || CONTINUE), () => { runtime.continueCount++; task.loopCount++; runtime.sendFailureCount = 0; runtime.lastContinueAt = Date.now(); runtime.lastAssistantTextHash = h; toast(`${audit ? "已触发最终自检" : "已自动发送继续"}（${runtime.continueCount}/${settings.maxContinueCount}）`); }, () => { runtime.sendFailureCount++; if (runtime.sendFailureCount >= 3) { runtime.pausedReason = "连续多次无法发送，自动继续已暂停"; task.status = "paused_send_failed"; toast(runtime.pausedReason); } }); }

  function scrollBottom() { if (Date.now() - lastUserScroll < settings.userScrollPauseMs) return; programmaticScrollUntil = Date.now() + 500; scrollTo(0, document.documentElement.scrollHeight || document.body.scrollHeight); Array.from(document.querySelectorAll("main,[role='main'],[class*='scroll'],[data-testid*='conversation'],div")).filter((el) => visible(el) && el.scrollHeight - el.clientHeight > 80).sort((a, b) => (b.scrollHeight - b.clientHeight) - (a.scrollHeight - a.clientHeight)).slice(0, 4).forEach((el) => el.scrollTop = el.scrollHeight); }
  function assist() { if (!settings.enabled) return; if (settings.keepAtBottom) scrollBottom(); if (settings.autoContinue) maybeContinue(); }
  function requestAssist() { if (document.visibilityState === "hidden") { const now = Date.now(); if (now - lastHiddenAssist < 500) return; lastHiddenAssist = now; assist(); return; } if (assistTimer) return; assistTimer = delay(() => { assistTimer = 0; assist(); }, 350); }
  function own(n) { return n instanceof Element && (n.id === `${APP_ID}-toast` || n.closest?.(`#${APP_ID}-panel`)); }
  function ownMut(m) { if (own(m.target)) return true; const nodes = [...m.addedNodes, ...m.removedNodes]; return nodes.length && nodes.every(own); }
  function cand(el, deep = false) { return el instanceof Element && (el.matches(BTN) || el.matches(DLG) || el.closest(DLG) || ((deep || el.childElementCount <= 80) && el.querySelector(`${BTN},${DLG}`))); }
  function scanMut(m) { if (ownMut(m)) return false; if (m.type === "characterData") return !!m.target.parentElement?.closest(BTN); if (m.type === "attributes") return cand(m.target); return [...m.addedNodes, ...m.removedNodes].some((n) => cand(n, true)); }
  function assistMut(m) { if (ownMut(m) || !settings.enabled || (!settings.keepAtBottom && !settings.autoContinue)) return false; const may = (n) => n instanceof Element && (n.matches("main,article,form,textarea,[contenteditable='true'],[data-message-author-role]") || n.closest("main,article,form,[data-message-author-role]") || (n.childElementCount <= 120 && n.querySelector("article,form,textarea,[contenteditable='true'],[data-message-author-role]"))); return m.type === "attributes" ? may(m.target) : (m.type === "characterData" ? [m.target.parentElement] : [...m.addedNodes, ...m.removedNodes]).some(may); }
  function loops() { clear(scanLoop); clear(assistLoop); if (settings.enabled && settings.autoConfirm) scanLoop = every(scan, 1000); if (settings.enabled && (settings.keepAtBottom || settings.autoContinue)) assistLoop = every(assist, 1500); }
  function state() { return { connected: true, enabled: settings.enabled, candidateText: candidate ? text(candidate) : "", scanInfo: { ...scanInfo }, automation: { ...runtime, maxContinueCount: settings.maxContinueCount }, task: { ...task, finalValid: task.lastGateReason === "valid_final", hasFinal: !!task.lastFinal }, settings: { ...settings } }; }
  function resetTask() { task = blankTask(); Object.assign(runtime, { continueCount: 0, sendFailureCount: 0, lastContinueAt: 0, lastAssistantTextHash: "", pausedReason: "" }); }
  function popup(msg, _sender, sendResponse) { if (msg?.source !== `${APP_ID}-popup`) return false; (async () => { if (msg.action === "confirm") manualClick(); else if (msg.action === "rescan") scan(); else if (msg.action === "reset-task") resetTask(); else if (msg.action === "set-setting" && Object.prototype.hasOwnProperty.call(DEF, msg.key)) { const v = msg.valueType === "number" ? Number(msg.value) : msg.valueType === "string" ? String(msg.value ?? "") : Boolean(msg.value); settings = cleanSettings({ ...settings, [msg.key]: v }); if (msg.key === "autoContinue" && v) runtime.pausedReason = ""; await saveSettings(); loops(); requestScan(); requestAssist(); } else if (msg.action === "get-state") scan(); sendResponse(state()); })().catch(() => sendResponse(state())); return true; }
  function cleanup() { ac.abort(); observer?.disconnect(); [scanTimer, assistTimer, scanLoop, assistLoop].forEach(clear); timers.forEach((id) => { clearTimeout(id); clearInterval(id); }); timers.clear(); clearMark(); document.getElementById(`${APP_ID}-toast`)?.remove(); chrome.runtime?.onMessage?.removeListener(popup); }
  window.__safeConfirmHelperCleanup = cleanup;
  document.addEventListener("keydown", (e) => { if (e.altKey && e.shiftKey && e.key === "Enter") { e.preventDefault(); manualClick(); return; } if (e.key === "Enter" && !e.shiftKey && !e.altKey && !e.ctrlKey && !e.metaKey && !e.isComposing && e.target instanceof Element && e.target.matches("#prompt-textarea,textarea,[contenteditable='true']")) prepare(e.target); }, { capture: true, signal: ac.signal });
  document.addEventListener("submit", (e) => { const el = input(e.target instanceof Element ? e.target : document); if (el) prepare(el); }, { capture: true, signal: ac.signal });
  const pointer = (e) => { const b = e.target instanceof Element ? e.target.closest("button") : null; if (b && /发送|send/i.test(text(b))) { const el = input(); if (el) prepare(el); } };
  document.addEventListener("pointerdown", pointer, { capture: true, signal: ac.signal });
  document.addEventListener("click", pointer, { capture: true, signal: ac.signal });
  document.addEventListener("visibilitychange", () => { lastHiddenScan = 0; lastHiddenAssist = 0; requestScan(); requestAssist(); }, { signal: ac.signal });
  document.addEventListener("scroll", () => { if (Date.now() > programmaticScrollUntil) lastUserScroll = Date.now(); }, { capture: true, passive: true, signal: ac.signal });
  chrome.runtime?.onMessage?.addListener(popup);
  (async () => { settings = await loadSettings(); observer = new MutationObserver((ms) => { if (ms.some(scanMut)) requestScan(); if (ms.some(assistMut)) requestAssist(); }); observer.observe(document.documentElement, { childList: true, subtree: true, attributes: true, characterData: true, attributeFilter: ["aria-disabled", "disabled", "hidden", "style", "class", "open"] }); loops(); requestScan(); requestAssist(); console.log("[Safe Confirm Helper] SCH_FINAL 长任务监督已启用。快捷键：Alt + Shift + Enter。"); })().catch((e) => console.error("[Safe Confirm Helper] 启动失败", e));
})();
